version: "3.4"
services:
  # beacon-chain:
  #   image: "beacon-chain.prysm-prater:mgarciate"
  #   build:
  #     context: beacon-chain
  #     args:
  #       UPSTREAM_VERSION: v2.0.6
  #   volumes:
  #     - "beacon-chain-data:/data"
  #   ports:
  #     - "13000"
  #     - 12000/udp
  #   restart: unless-stopped
  #   environment:
  #     HTTP_WEB3PROVIDER: "http://goerli-geth.dappnode:8545"
  validator:
    image: "validator.prysm-prater:mgarciate"
    build:
      context: validator
      args:
        BRANCH: develop
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain.prysm-prater.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-prater.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
    ports:
      - "7080:80"
  web3signer:
    build:
      context: web3signer
      args:
        UPSTREAM_VERSION: 21.10.5
    image: consensys/web3signer:mgarciate
    command: ["--key-store-path=/keyfiles",
            "--http-listen-port=9003",
            "--http-listen-host=0.0.0.0",
            "--http-host-allowlist=*",
            "eth2",
            "--slashing-protection-enabled=false",
            "--network=prater"]
    volumes:
      - $PWD/keyfiles:/keyfiles
    ports:
      - "9003:9000"
volumes:
  validator-data: {}
  # beacon-chain-data: {}
